version: "3.8"


services:
  nginx:
    container_name: web-project_nginx
    image: registry.gitlab.com/bryanmramsamy/icc-projetdeveloppementweb_2019-2020/nginx
    ports:
      - "8000:80"
    links:
      - phpfpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log


  phpfpm:
    container_name: web-project_phpfpm
    build: .
    image: registry.gitlab.com/bryanmramsamy/icc-projetdeveloppementweb_2019-2020/phpfpm
    links:
      - database:mysql
    volumes:
      - ./public:/usr/share/nginx/html


  database:
    container_name: web-project_database
    image: registry.gitlab.com/bryanmramsamy/icc-projetdeveloppementweb_2019-2020/database
    volumes:
      - type: volume
        source: lemp_database
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin


  phpmyadmin:
    container_name: web-project_phpmyadmin
    image: registry.gitlab.com/bryanmramsamy/icc-projetdeveloppementweb_2019-2020/phpmyadmin
    restart: unless-stopped
    links:
      - database:mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
      PMA_ARBITRARY: 1


volumes:
  lemp_database:
